quickstart/php/web/plugins/curl_plugin.php
=> Fix Bug : add closed parenthesis

pinpoint_common/agent_monitor_sender.cpp, pinpoint_common/api_data_sender.cpp, pinpoint_common/log_utility.cpp, pinpoint_common/pinpoint_agent.cpp, pinpoint_common/pinpoint_api.cpp, pinpoint_common/pinpoint_api.h, pinpoint_common/serializer.cpp, pinpoint_common/string_data_sender.cpp, pinpoint_common/trace_data_sender.cpp, pinpoint_php/pinpoint_ext.cpp, simulate/conf/pinpoint_agent.conf
DEBUG < TRACE < INFO < WARNING< ERROR < STDERR
=> add trace log level

pinpoint_common/pinpoint_client.cpp, pinpoint_common/pinpoint_client.h, pinpoint_php/plugins/request_plugin.cpp
1. Fix trace limit is enable (crash)
2. Reconnect with timeout
=> Trace limit bug

PHP/pinpoint_php_example/composer.json, README.md
=> [8-14] add related issues

PHP/pinpoint_php_example/composer.json
=> Support macOS compiling problems

PHP/pinpoint_php_example/Readme.md, README.md
=> [8-16] update dev-2 to dev

quickstart/php/web/plugins/curl_plugin.php, simulate/web/php/plugins/curl_plugin.php
fix the bug when header not exist. #93
=> [8-9] fix header unexist

PHP/pinpoint_php_ext/common.h, PHP/pinpoint_php_ext/pinpoint_helper.h
=> [8-16] fix unit missing

PHP/pinpoint_php_example/app/AopFunction.php
=> Modify testcase.

README.md
=> [8-28] add gitter

config.m4, src/PHP/tests5/aop_helper_api.phpt, src/PHP/tests5/app_info_test.phpt, src/PHP/tests5/drop_trace_test.phpt, src/PHP/tests5/stack_fetal_error.phpt, src/PHP/tests5/trace_api_test.phpt, src/PHP/tests5/trace_limit_test.phpt, src/PHP/tests5/unique_api_test.phpt
=> add php5 tests5

.travis.yml, src/PHP/tests5/aop_helper_api.phpt
=> enable REPORT_EXIT_STATUS

collector-agent/conf/collector.conf
=> amend collector.conf

DOC/PHP/Readme-CN.md, DOC/PHP/Readme.md, DOC/PHP/SupportPlan.md, DOC/PHP/User Manual-CN.md, DOC/PHP/User Manual.md, DOC/PHP/detail_versions-CN.md, DOC/PHP/detail_versions.md, DOC/PY/Readme-CN.md, DOC/PY/Readme.md, testapps/PHP/Readme.md
=> Optimize doc

DOC/PHP/Readme-CN.md, DOC/PHP/Readme.md, DOC/PHP/User Manual-CN.md, DOC/PHP/User Manual.md, DOC/PHP/detail_versions-CN.md, DOC/PHP/detail_versions.md, DOC/PY/Readme-CN.md, DOC/PY/Readme.md, DOC/PY/SupportPlan.md, plugins/PHP/Plugins/AutoGen/app/CommonPlugin.php, plugins/PHP/Plugins/AutoGen/app/Generator.php, plugins/PHP/Plugins/AutoGen/app/GeneratorPlugin.php
Modify DOC and generator plugin.
=> Modify DOC and generator plugin.

DOC/PHP/Readme.md, plugins/PY/Readme.md
=> Modify DOC.

plugins/PY/pinpoint/common/Span.py, plugins/PY2.7/pinpoint/plugins/common/Span.py
=> Add tid use start_time

README.md
=> Update CI location

README.md
=> remove URL

plugins/PY/pinpoint/common/__init__.py
Checking 
```py
if __python_version >="3.7":
=> Exclude Asyn* in sync

plugins/PHP/Plugins/AutoGen/SwooleApp/UserPlugin.php, plugins/PHP/Plugins/AutoGen/app/CommonPlugin.php, plugins/PHP/Plugins/AutoGen/app/Generator.php, plugins/PHP/Plugins/AutoGen/app/GeneratorPlugin.php, plugins/PHP/Plugins/Common/CommonPlugin.php, testapps/PHP/Readme.md
=> fix: remove fetch data by print_r

collector-agent/Events/StreamServerLayer.py, common/include/common.h, common/src/NodePool/PoolManager.cpp, common/src/NodePool/TraceNode.h, common/src/common.cpp, plugins/PHP/Plugins/AutoGen/SwooleApp/UserPlugin.php, plugins/PHP/Plugins/AutoGen/app/CommonPlugin.php, plugins/PHP/Plugins/AutoGen/app/Generator.php, plugins/PHP/Plugins/AutoGen/app/GeneratorPlugin.php, plugins/PHP/Plugins/Common/CommonPlugin.php, testapps/PHP/Readme.md
=> Fix big span

common/src/Cache/Chunk.cpp, common/src/Cache/Chunk.h, common/src/ConnectionPool/TransLayer.cpp, common/src/ConnectionPool/TransLayer.h, common/src/common.cpp
Update event when buffer is full
=> Fix: pending when buffer is full

collector-agent/CollectorAgent/GrpcAgentImplement.py, collector-agent/CollectorAgentConf/CollectorAgentConf.py, collector-agent/CollectorAgentConf/__init__.py, collector-agent/Common/AgentHost.py, collector-agent/Common/__init__.py, collector-agent/Events/StreamServerLayer.py, collector-agent/PHPAgent/FrontAgent.py, collector-agent/PinpointAgent/AppManagement.py, collector-agent/PinpointAgent/__init__.py, collector-agent/Test/test_implement.py, collector-agent/run.py, common/src/Cache/Chunk.h, common/src/NodePool/PoolManager.cpp, common/src/common.cpp, common/test/test_node_pool.cc
Collector-agent maybe pend the income
=> fix(Full and pending): fork and  clean fron-agent

common/src/ConnectionPool/TransLayer.cpp, common/src/ConnectionPool/TransLayer.h, plugins/PHP/Plugins/Common/PluginsDefines.php, plugins/PHP/Plugins/Framework/yii2/Readme.md, plugins/PHP/Plugins/PerRequestPlugins.php, plugins/PHP/Plugins/Readme.md
=> F mem usage

src/PHP/pinpoint_php.cpp
=> fix: compile problem

Changes.md
=> docs: v0.4.1

collector-agent/CollectorAgent/ThriftAgentImplement.py, collector-agent/Common/__init__.py, collector-agent/run.py
ThriftAgentImplement , not working
=> fix: thrift gevent loop dead loop

src/PY/pinpoint_py.c, src/PY/test/TestUnderProcessMode.py, src/PY/test/TestUnderThreadMode.py
=> fix: drop_trace will crash

common/src/Cache/SafeSharedState.cpp, src/PHP/tests/trace_limit_test-i448.phpt, src/PHP/tests5/trace_limit_test-i448.phpt
=> fix: limit=0

src/PY/pinpoint_py.c, src/PY/test/TestCoroutines.py, src/PY/test/TestPinpoint.py, src/PY/test/TestUnderProcessMode.py, src/PY/test/TestUnderThreadMode.py
* get_context_key
* force_flush_trace(timeout=3,
=> test: python testcase

plugins/PY/pinpoint/Django/BaseDjangoRequestPlugins.py, plugins/PY/pinpoint/Flask/FlaskPlugins.py, plugins/PY/pinpoint/Flask/PinPointMiddleWare.py
Add request method and status code in PerRequestPlugin.
=> Add request method and status code in PerRequestPlugin.

Changes.md, plugins/PY/pinpoint/libs/MySQLdb/MysqldbPlugin.py, plugins/PY/pinpoint/libs/MySQLdb/__init__.py
=> feat: [py] MySQLdb

collector-agent/CollectorAgent/GrpcAgentImplement.py, collector-agent/PinpointAgent/AppManagement.py
=> style: logging

plugins/PHP/Plugins/Common/InstancePlugins.php
`INTERCEPTER_NAME` is the old define name constant need to be change into `PP_INTERCEPTOR_NAME`
=> Fix PP_INTERCEPTOR_NAME

plugins/PHP/Plugins/PerRequestPlugins.php
* Add in `PP_INTERCEPTOR_NAME` the sapi context to define if it's a cgi, fpm, cli, request.
* IF `REQUEST_URI` doesn't exist fail over to get the arguments provide to the CLI
* In non http context variable of type `HTTP_XXX`, `REMOTE_XXX` doesn't exist so just checking if they exist avoid error.
=> Make PerRequestPlugins compatible for CLI request

collector-agent/CollectorAgent/GrpcSpanFactory.py, collector-agent/CollectorAgent/ThriftSpanFactory.py, collector-agent/PinpointAgent/AppManagement.py
=> refactor: No default header

README.md
=> chart room

collector-agent/CollectorAgent/GrpcAgent.py, collector-agent/CollectorAgent/GrpcStat.py, collector-agent/Common/Stat.py, collector-agent/Common/__init__.py, collector-agent/PinpointAgent/Type.py, common/test/test_common.cc
- upload a fack jvmGs
- ping more less
=> fix(collector-agent): jvmGs

plugins/PHP/Plugins/AutoGen/GuzzleHttp/GuzzlePlugin.php, plugins/PHP/Plugins/Framework/Swoole/curl/CurlUtil.php, plugins/PHP/Plugins/Framework/Swoole/curl/curl.php, plugins/PHP/Plugins/Sys/curl/CurlExecPlugin.php, plugins/PHP/Plugins/Sys/curl/CurlUtil.php, plugins/PHP/Plugins/Sys/curl/curl.php, plugins/PY/pinpoint/common/Span.py, plugins/PY/pinpoint/libs/requests/NextSpanPlugin.py, plugins/PY/pinpoint/libs/urllib/UrlOpenPlugin.py
=> fix: unknow node

DOC/PY/Readme.md, collector-agent/conf/env.file
add env.file for collector-agent docker
=> docs: docker

plugins/PY/pinpoint/celeryWorker/WorkerPlugin.py, plugins/PY/pinpoint/celeryWorker/__init__.py, plugins/PY/pinpoint/libs/amqp/AMQPConsumerPlugin.py, plugins/PY/pinpoint/libs/amqp/AMQPPublicPlugin.py, plugins/PY/pinpoint/libs/celeryCaller/GetPlugin.py, plugins/PY/pinpoint/libs/celeryCaller/TaskPlugin.py, plugins/PY/pinpoint/libs/celeryCaller/__init__.py, plugins/PY/pinpoint/libs/internal/__init__.py, plugins/PY/pinpoint/libs/kombu/ProducerPlugin.py, plugins/PY/pinpoint/libs/kombu/__init__.py, plugins/PY/pinpoint/libs/librabbitmq/__init__.py
=> fix: celery plugins

collector-agent/CollectorAgent/GrpcAgent.py, collector-agent/CollectorAgent/ReqStat.py
=> refactor: ceil

testapps/PY/DBControl.py, testapps/PY/app.py, testapps/PY/test_return.py
=> fix(testapp-Py): fix bug in testapp-py

collector-agent/CollectorAgent/GrpcAgent.py, collector-agent/CollectorAgent/GrpcSpan.py
=>  refactor: logger，exit

DOC/PHP/Readme.md
=> docs: docs: php

DOC/PHP/Readme.md, DOC/PY/Readme.md
=> env.file-modified

collector-agent/CollectorAgent/GrpcAgent.py, collector-agent/CollectorAgent/GrpcClient.py, collector-agent/CollectorAgent/GrpcSpan.py
- new a channel when  fetal error happens
=> fix: Span Channel fetal error

collector-agent/CollectorAgent/GrpcAgent.py, collector-agent/CollectorAgent/GrpcAgentImplement.py, collector-agent/CollectorAgentConf/CollectorAgentConf.py, collector-agent/conf/collector.conf, plugins/PY/pinpoint/Django/BaseDjangoRequestPlugins.py, plugins/PY/pinpoint/celeryWorker/WorkerPlugin.py, plugins/PY/pinpoint/common/Span.py, plugins/PY/pinpoint/libs/celeryCaller/TaskPlugin.py, plugins/PY/pinpoint/libs/kombu/ProducerPlugin.py, plugins/PY/pinpoint/libs/requests/NextSpanPlugin.py, plugins/PY/pinpoint/settings.py
- fix celery unknow node
- fix isdocker setting
=> fix: celery confused appname

collector-agent/CollectorAgent/GrpcAgent.py, collector-agent/CollectorAgent/GrpcMeta.py, collector-agent/CollectorAgent/GrpcStat.py, collector-agent/Events/StreamServerLayer.py
=> fix: exist is pending

collector-agent/CollectorAgent/GrpcAgent.py
=> Bug handle cmd timeout

.github/workflows/main.yml, plugins/PY/pinpoint/Django/BaseDjangoRequestPlugins.py, plugins/PY/pinpoint/Flask/FlaskPlugins.py, plugins/PY/pinpoint/common/Common.py, plugins/PY/pinpoint/libs/DjangoRest/ViewsPlugin.py, plugins/PY/pinpoint/libs/DjangoRest/__init__.py, plugins/PY/pinpoint/libs/requests/NextSpanPlugin.py
Use isSample and support django-rest
=> feature(Python-Agent): Use isSample and support django-rest

plugins/PY/pinpoint/libs/MysqlConnector/CMysqlPlugin.py, plugins/PY/pinpoint/libs/MysqlConnector/MysqlPlugin.py, plugins/PY/pinpoint/libs/MysqlConnector/__init__.py
Support mysql-connector
Closes #486
=> feature(Python-Agent): Support mysql-connector

plugins/PY/pinpoint/Flask/FlaskPlugins.py, plugins/PY/pinpoint/common/Common.py, plugins/PY/pinpoint/common/Span.py, plugins/PY/pinpoint/libs/celeryTask/TaskPlugin.py, plugins/PY/pinpoint/libs/requests/NextSpanPlugin.py, plugins/PY/pinpoint/libs/urllib/UrlOpenPlugin.py
Span is not complete when call Recursion
Closes issues495
=> fix(python plugin): Recursion span incomplete

DOC/PHP/Readme-CN.md, DOC/PHP/Readme.md, DOC/PY/Readme-CN.md, DOC/PY/Readme.md
Modify Collector-Agent(go) doc
=> docs(Collector-Agent): Modify Collector-Agent(go) doc

collector-agent/agent/SpanSender.go, collector-agent/server/ServerEnv.go, collector-agent/server/SpanServer.go
=> fix: No panic

.dockerignore, .gitignore, DOC/API/common.h, common/CMakeLists.txt, common/include/common.h, common/pkg-config/pinpoint_common.pc, common/pkg-config/pinpoint_common.pc.in, common/src/Cache/SafeSharedState.cpp, common/src/Cache/SafeSharedState.h, common/src/Cache/SharedObj.c, common/src/Cache/SharedObj.h, common/test/test_trans_layer.cc, common/test/test_util.cc, src/PHP/pinpoint_php.cpp, src/PY/pinpoint_py.c
* support userid
* Storage starttime into shm
=> Refactor common library

CMakeLists.txt, collector-agent/common/Utils.go, common/CMakeLists.txt, common/CMakeLists.txt.in, common/include/common.h, common/src/ConnectionPool/TransLayer.h, setup.py, src/PHP/tests/trace_api_context_tcp.phpt, src/PHP/tests5/trace_api_context.phpt, src/PHP/tests5/trace_api_context_tcp.phpt
=> Bug index outofrange

collector-agent/start-collector-agent.sh
=> wrong location

DOC/collector-agent/readme.md, DOC/common/Readme.md
=> docs: Add docker

src/PHP/pinpoint_php.cpp, src/PHP/pinpoint_php_api.php, src/PHP/tests/mark_as_error.phpt
support mark_as_error in php agent
=> feat: mark_as_error 

.github/workflows/publish.yml, setup_test.py
Add action for release pinpointPy
=> Add action for release pinpointPy

.github/workflows/codeql-analysis.yml
=> Test codeql

common/src/NodePool/PoolManager.cpp, common/src/common.cpp
Wrong type of arguments to formatting function
=> style(style:-code-scanning)

common/src/Cache/SafeSharedState.cpp, common/src/ConnectionPool/TransLayer.cpp, common/src/common.cpp
=> Test style

common/src/ConnectionPool/SpanConnectionPool.cpp, common/src/ConnectionPool/SpanConnectionPool.h, common/src/Util/Helper.cpp, common/src/common.cpp, common/test/test_trans_layer.cc, src/PHP/php_pinpoint_php.h, src/PHP/pinpoint_php.cpp
#296 
Cli + pinpoint- php , php agent
=> feat(Cli-+pinpoint-php): Support cli, running in container

.github/workflows/publish-test.yml, .github/workflows/publish.yml
=> Modify publish action

DOC/common/Readme.md
=> Modify common install step

plugins/PY/pinpoint/libs/__init__.py
=> fix:  #321

src/PHP/pinpoint_php.cpp
Just to make error message align with the function name
=> Small change for label to be align with function name

plugins/PHP/Plugins/PerRequestPlugins.php
Mark transaction as failed if return code is 5xx
=> Mark request as failed if return 5xx return code

.github/workflows/add-contributors.yml, README.md
update contributors by BobAnkh/add-contributors@master
=> style: add Contributors

.github/workflows/main.yml, src/PHP/tests/trace_api_context.phpt, src/PHP/tests/trace_api_context_tcp.phpt, src/PHP/tests/trace_limit_test-i448.phpt, src/PHP/tests5/trace_api_context.phpt, src/PHP/tests5/trace_api_context_tcp.phpt, src/PHP/tests5/trace_limit_test-i448.phpt
=> Test php5.4

plugins/PHP/Framework/ThinkPHP5/setting.ini
Plugins\Sys\PDO\PDO -> Pinpoint\Plugins\Sys\PDO\PDO
=> Error in setting.ini

collector-agent/agent/SpanSender.go
1. ERR > EXP
2. fix nil in `ExceptionInfo`
=> Fix EXP within per-request

.github/workflows/main.yml, .github/workflows/publish-test.yml, src/PHP/pinpoint_php.cpp
* pinpoint_php module support php8.1.x
* to https://github.com/pinpoint-apm/pinpoint-c-agent/issues/379
=> support php8.1 style

plugins/PHP/Framework/ThinkPHP5/setting.ini
=> add phpredis in tp5

.gitignore, plugins/PHP/Framework/laravel/Readme.md, plugins/PHP/Framework/laravel/setting.ini
=> enable laravel

setup_pypi_test.py
=> fix wrong file name

README.md
=> [doc]Support Lists

common/include/common.h, common/src/NodePool/TraceNode.cpp, common/src/NodePool/TraceNode.h, common/src/common.cpp, common/test/test_node_pool.cc
* avoiding unexecpted problems in multiple-thread
=> [enh] add lock in TraceNode

plugins/PY/pinpointPy/Fastapi/AsyCommon.py, plugins/PY/pinpointPy/Fastapi/AsyCommonPlugin.py, plugins/PY/pinpointPy/Fastapi/AsyRequestPlugin.py, plugins/PY/pinpointPy/Fastapi/__init__.py, plugins/PY/pinpointPy/common/AsyCommon.py, plugins/PY/pinpointPy/common/AsyCommonPlugin.py, plugins/PY/pinpointPy/common/AsyRequestPlugin.py, plugins/PY/pinpointPy/common/WSGIPlugin.py, plugins/PY/pinpointPy/libs/aioHttp/pymongo/MongoClientPlugin.py, plugins/PY/pinpointPy/tornado/CommonPlugin.py, plugins/PY/pinpointPy/tornado/HTTPRequestPlugins.py, plugins/PY/pinpointPy/tornado/PinpointAsyCommon.py, setup_pypi_test.py
* AsyCandy->AsynPinTrace
* export Fastapi
=> [style] rename candy

plugins/PY/pinpointPy/Fastapi/AsyRequestPlugin.py
fix line break in AsyRequestPlugin
=> fix line break in AsyRequestPlugin

setup_pypi_test.py
=> pinpointPy testpy 1.0.17

setup_pypi_test.py, testapps/PY/Readme-CN.md, testapps/PY/Readme.md, testapps/PY/app.py, testapps/PY/app1/user_function.py, testapps/PY/doctor.py, testapps/PY/person.py, testapps/PY/student.py, testapps/PY/teacher.py, testapps/PY/test_abstract.py, testapps/PY/test_args.py, testapps/PY/test_band.py, testapps/PY/test_decorator.py, testapps/PY/test_exception.py, testapps/PY/test_function.py, testapps/PY/test_generatior.py, testapps/PY/test_higher_order.py, testapps/PY/test_lambda.py, testapps/PY/test_mixin.py, testapps/PY/test_partial.py, testapps/PY/test_private.py, testapps/PY/test_recursion.py, testapps/PY/test_return.py, testapps/PY/test_returns.py, testapps/PY/test_special.py, testapps/PY/test_static_class_method.py
=> Fix testapp

setup_pypi.py, setup_pypi_test.py
> dl_cd_pinpoint
* update email
* update author
=> [style] update version id

collector-agent/agent/GrpcAgent.go, collector-agent/agent/MetaData.go, collector-agent/agent/SpanSender.go
=> [enh] retry when metadata failed

common/Dockerfile, common/Go1.16.Dockerfile
=> [ci] build base image

README.md
=> style: fold

.github/workflows/main.yml, testapps/PHP/application/common/TestGuzzle.php
=> CI-stablity

DOC/PHP/Readme-KR.md, DOC/PY/Readme-KR.md
=> add KR readme

README.md
=> add kr link

plugins/PY/pinpointPy/Fastapi/AsyCommon.py, plugins/PY/pinpointPy/Fastapi/AsyRequestPlugin.py, plugins/PY/pinpointPy/Fastapi/FastAPIRequestPlugin.py, plugins/PY/pinpointPy/pinpoint.py, setup_pypi.py, setup_pypi_test.py
=> support fastapi framework.

README.md
add collector-agent installation in readme
=> add collector-agent installation in readme

common/include/common.h, common/src/ConnectionPool/TransLayer.cpp, common/src/ConnectionPool/TransLayer.h, common/src/NodePool/TraceNode.cpp, common/src/NodePool/TraceNode.h, common/src/common.cpp, common/test/test_node.cc, common/test/test_trans_layer.cc
* testcase for threads
* clues thread safe
=> [enh] multiple-thread api

.gitignore, common/CMakeLists.txt, common/include/common.h.in, common/readme.md, common/src/NodePool/TraceNode.h, common/src/common.cpp, common/test/test_common.cc, common/test/test_node.cc
=> [enh] add cumulative_time

README.md
=> add show more

plugins/PY/pinpointPy/Fastapi/AsyCommon.py, plugins/PY/pinpointPy/Fastapi/aioredis/AioRedisPlugins.py, plugins/PY/pinpointPy/Fastapi/aioredis/__init__.py, setup_pypi_test.py
support fastapi+redis.
monitor aioredis.
=> support fastapi+redis

src/CPP/test_pinpoint.c
=> [fix] E_CURRENT_LOC

common/test/test_node.cc
=> [test] more case on node pool

common/src/common.cpp
status["common_libary_version"] = pinpoint_agent_version();
=> [test] common_libary_version

.github/workflows/main.yml, common/CMakeLists.txt, common/include/common.h.in, common/src/Context/ContextType.h, common/src/NodePool/TraceNode.h, common/src/Util/Helper.cpp, common/src/common.cpp, common/test/test_common.cc, common/test/test_node.cc, setup_pypi.py, setup_pypi_test.py, src/PHP/pinpoint_php.cpp, src/PY/_pinpoint_py.c
* getContextByKey
* mergeChildren: copy, not ref
=> [enh] pretect context

common/CMakeLists.txt, common/src/NodePool/PoolManager.cpp, common/src/NodePool/PoolManager.h, common/src/NodePool/TraceNode.cpp, common/src/NodePool/TraceNode.h, common/src/Util/Helper.cpp, common/src/Util/Helper.h, common/src/common.cpp, common/src/header.h, common/test/test_common.cc, common/test/test_node.cc, common/test/test_node_pool.cc, common/test/test_util.cc
* WrapperTraceNode with TraceNode
* test-case
=> [enh] try to fix node leak under mt mode
